abstracta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('rest_tiendita.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import home, registro, contacto, agregar_producto, listar_productos, \
    modificar_producto, eliminar_producto, catalogo, clima, carrito, pagar, settings, \
    historial, direcciones, cupones, metodos_de_pago, despacho, pago

urlpatterns = [
    path('', home, name = "home"),
    path('registro/', registro, name = 'registro'),
    path('contacto/', contacto, name = 'contacto'),
    path('catalogo/', catalogo, name = 'catalogo'),
    path('agregar-producto/', agregar_producto, name = "agregar_producto"),
    path('listar-productos/', listar_productos, name = 'listar_productos'),
    path('modificar-producto/<id>/', modificar_producto, name = "modificar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name = "eliminar_producto"),
    path('clima/', clima, name = "clima"),
    path('carrito/', carrito, name = "carrito"),
    path('settings/', settings, name = 'settings'),
    path('settings/historial/', historial, name = 'historial'),
    path('settings/direcciones/', direcciones, name = 'direcciones'),
    path('settings/cupones/', cupones, name = 'cupones'),
    path('settings/metodos_de_pago/', metodos_de_pago, name = 'metodos_de_pago'),
    path('settings/despacho/', despacho, name = 'despacho'),
    path('pagar', pagar, name = 'pagar'),
    path('pago', pago, name = 'pago'),
]

app/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombreCat = models.CharField(max_length = 50)
    def __str__(self):
        return self.nombreCat

class Producto(models.Model):
    nombreProducto = models.CharField(max_length = 50, verbose_name= 'Nombre del Producto')
    precioProducto = models.IntegerField(verbose_name= 'Precio del producto')
    descripcionProducto = models.TextField(verbose_name= 'Descripcion del producto')
    imagen = models.ImageField(upload_to = 'productos', null = True)
    nombreCat = models.ForeignKey(Categoria, on_delete = models.PROTECT)
    def __str__(self):
        return self.nombreProducto

opciones_consultas = [
    [0, 'Consulta'],
    [1, 'Reclamo por error'],
    [2, 'Sugerencia'],
]

class Contacto(models.Model):
    nombre = models.CharField(max_length = 50)
    correo = models.EmailField()
    tipo_contacto = models.IntegerField(choices = opciones_consultas) 
    mensaje = models.TextField()
    avisos = models.BooleanField()
    def __str__(self):
        return self.nombre

opciones_pago = [
    [0, 'Transferencia bancaria'],
    [1, 'Tarjeta de debito'],
    [2, 'Tarjeta de crédito'],
]

class Datos(models.Model):
    nombre = models.CharField(max_length = 50)
    telefono = models.IntegerField(verbose_name = 'Numero de contacto')
    correo = models.EmailField()
    metodo_pago = models.IntegerField(choices = opciones_pago) 
    cupon = models.IntegerField(verbose_name = 'Cupon de descuento')
    def __str__(self):
        return self.nombre

app/templates/app/producto/agregar.html
{% extends 'app/base.html' %}
{% block content %}
{% block title %}Agregar producto{% endblock title %}
{% load crispy_forms_tags %}
<br>
<br>
<div class="container mb-4">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3 mb-md-5 mt-md-4 pb-5">
            <div class="card bg-dark text-white">
                <div class="card-body p-5 text center fs-4 ">
                    <h2>Ingresar producto</h2>
                    <hr>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <input class="btn btn-secundary" type="reset" value="Cancelar" style="background-color: rgb(255, 230, 0)">
                            &nbsp;
                            <input class="btn btn-primary" type="submit" value="Guardar">
                        </div>
                    </form>
                    {{ mensaje }}
                </div>
            </div>
        </div>
    </div>
</div>
    
{% endblock %}

app/templates/app/producto/listar.html
{% extends 'app/base.html' %}
{% block title %}Listar productos{% endblock title %}
{% block js %}
<script>
    function eliminarProducto(id) {
        Swal.fire({
            'title': '¿Estas seguro?',
            'text': 'Esta acción no se puede deshacer',
            'icon': 'question',
            'showCancelButton': true,
            'cancelButtonTest': 'No, cancelar',
            'confirmButtonText': 'Si, eliminar',
            'reverseButtons': true,
            'confirmButtonColor': '#dc3545',
        })
            .then(function (result) {
                if (result.isConfirmed) {
                    window.location.href = "/eliminar-producto/" + id + "/"
                }
            });
    }
</script>
{% endblock %}
{% block content %}
{% load humanize %}
<br>
<br>
<br>
<div class="container">
    <div class="card bg-dark text-white">
        <div class="card-body ">
            <h2>Listado de productos</h2>
            <hr>
        </div>
        <table class="table table-dark table-striped table-hover table-responsive-sm fs-4">
            <tr>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Precio</th>
                <th>Categoria</th>
                <th>Opciones</th>
            </tr>
            {% for p in entity %}
            <tr>
                <td>{{ p.nombreProducto | title }}</td>
                <td>{{ p.descripcionProducto | title }}</td>
                <td>{{ p.precioProducto | intcomma }}</td>
                <td>{{ p.nombreCat | title }}</td>
                <td>
                    {% if perms.app.change_producto %}
                    <a class="btn btn-info btn-sm" href="{% url 'modificar_producto' p.id %}">Modificar</a>
                    {% endif %}
                    {% if perms.app.delete_producto %}
                    <a class="btn btn-danger btn-sm" href="#" onclick="eliminarProducto({{ p.id }})">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <hr>
        <div>
            {% include 'app/paginator.html' %}
        </div>
    </div>
    <br>
    <br>
    <br>
</div>
<script>
    let menu = document.getElementById("menu")
    let header = document.getElementById("header")
    let nav = document.getElementById("nav")
    menu.addEventListener("click", function () {
        if (header.style.height == "60px" || header.offsetHeight == 60) {
            header.style.height = 60 + nav.offsetHeight + "px"
        } else {
            header.style.height = "60px"
        }
    });

    window.addEventListener("resize", function () {
        let anchoVentana = document.documentElement.clientWidth
        if (anchoVentana > 480) {
            header.style = "none"
        }
    });
</script>
{% endblock %}

app/templates/app/producto/modificar.html
{% extends 'app/base.html' %}
{% block content %}
{% block title %}Modificar{% endblock title %}
{% load crispy_forms_tags %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h2>Modificar producto</h2>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <input class="btn btn-danger" type="reset" value="Cancelar">
                            &nbsp;
                            <input class="btn btn-primary" type="submit" value="Editar">
                        </div>
                    </form>
                    {{ mensaje }}
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
{% endblock %}