abstracta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('rest_tiendita.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import home, registro, contacto, agregar_producto, listar_productos, \
    modificar_producto, eliminar_producto, catalogo, clima, carrito, pagar, settings, \
    historial, direcciones, cupones, metodos_de_pago, despacho, pago

urlpatterns = [
    path('', home, name = "home"),
    path('registro/', registro, name = 'registro'),
    path('contacto/', contacto, name = 'contacto'),
    path('catalogo/', catalogo, name = 'catalogo'),
    path('agregar-producto/', agregar_producto, name = "agregar_producto"),
    path('listar-productos/', listar_productos, name = 'listar_productos'),
    path('modificar-producto/<id>/', modificar_producto, name = "modificar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name = "eliminar_producto"),
    path('clima/', clima, name = "clima"),
    path('carrito/', carrito, name = "carrito"),
    path('settings/', settings, name = 'settings'),
    path('settings/historial/', historial, name = 'historial'),
    path('settings/direcciones/', direcciones, name = 'direcciones'),
    path('settings/cupones/', cupones, name = 'cupones'),
    path('settings/metodos_de_pago/', metodos_de_pago, name = 'metodos_de_pago'),
    path('settings/despacho/', despacho, name = 'despacho'),
    path('pagar', pagar, name = 'pagar'),
    path('pago', pago, name = 'pago'),
]

app/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombreCat = models.CharField(max_length = 50)
    def __str__(self):
        return self.nombreCat

class Producto(models.Model):
    nombreProducto = models.CharField(max_length = 50, verbose_name= 'Nombre del Producto')
    precioProducto = models.IntegerField(verbose_name= 'Precio del producto')
    descripcionProducto = models.TextField(verbose_name= 'Descripcion del producto')
    imagen = models.ImageField(upload_to = 'productos', null = True)
    nombreCat = models.ForeignKey(Categoria, on_delete = models.PROTECT)
    def __str__(self):
        return self.nombreProducto

opciones_consultas = [
    [0, 'Consulta'],
    [1, 'Reclamo por error'],
    [2, 'Sugerencia'],
]

class Contacto(models.Model):
    nombre = models.CharField(max_length = 50)
    correo = models.EmailField()
    tipo_contacto = models.IntegerField(choices = opciones_consultas) 
    mensaje = models.TextField()
    avisos = models.BooleanField()
    def __str__(self):
        return self.nombre

opciones_pago = [
    [0, 'Transferencia bancaria'],
    [1, 'Tarjeta de debito'],
    [2, 'Tarjeta de crédito'],
]

class Datos(models.Model):
    nombre = models.CharField(max_length = 50)
    telefono = models.IntegerField(verbose_name = 'Numero de contacto')
    correo = models.EmailField()
    metodo_pago = models.IntegerField(choices = opciones_pago) 
    cupon = models.IntegerField(verbose_name = 'Cupon de descuento')
    def __str__(self):
        return self.nombre

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %} - Tiendita</title>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'js/clock.js' %}"></script>

    <!-- MomentJS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/locale/es-mx.min.js"></script>

    {% block css %}
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/bxslider/dist/jquery.bxslider.css' %}">
    <link rel="preload" href="{% static 'css/normalize2.css' %}" as="style">
    <link rel="stylesheet" href="{% static 'css/normalize2.css' %}">
    <link rel="preload" href="{% static 'css/stail.css' %}" as="style">
    <link rel="stylesheet" href="{% static 'css/stail.css' %}">
    <link rel="preload" href="{% static 'css/estilos3.css' %}" as="style">
    <link rel="stylesheet" href="{% static 'css/estilos3.css' %}">
    <link rel="preload" href="{% static 'css/estail.css' %}" as="style">
    <link rel="stylesheet" href="{% static 'css/estail.css' %}">
    <link rel="preload" href="{% static 'css/stail3_2.css' %}" as="style">
    <link rel="stylesheet" href="{% static 'css/stail3_2.css' %}">
    <link rel="preload" href="{% static 'css/responsive_4_1.css' %}" as="style">
    <link rel="stylesheet" href="{% static 'css/responsive_4_1.css' %}">

    {% endblock %}
</head>
<body class="gradient-custom">
    <header id="header">
        <img class="menu" id="menu" src="/static/img/menuiconwhite.png" alt="menu">
        <div class="contenedor_logo">
            <img class="logo" src="{% static 'img/logo.png' %}" alt="logo">
            <a href="{% url 'home' %}" style="color:black;"><h2 style="color:white;">Abstracta</h2></a>
            <p class="reloj" id="reloj"></p>
            <div id="contenedor__carrito">
                <a class="nav__fonts" href="{% url 'carrito' %}"><i class="bi bi-cart3"></i></a>
            </div>
        </div>
        <div>
            <nav class="h5" id="nav">
                <ul>
                    <li><a href="{% url 'home' %}"> Inicio </a></li>
                    <li><a href="{% url 'clima' %}"> Clima </a></li>
                    <li><a href="{% url 'contacto' %}">Contacto</a></li>
                    <li><a href="{% url 'catalogo' %}">Nuestros Productos!</a></li>
                    {% if perms.app.add_producto %}
                    <li><a href="{% url 'agregar_producto' %}">Agregar producto</a></li>
                    {% endif %}
                    {% if perms.app.view_producto %}
                    <li><a href="{% url 'listar_productos' %}">Listado Productos</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'settings' %}">Configuraciones</a></li>
                    <li><a href="{% url 'logout' %}">Cerrar sesion</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Iniciar Sesión</a></li>
                    <li><a href="{% url 'registro' %}">Registrarse</a></li>
                    {% endif %}
                    <li><a href="{% url 'carrito' %}"><i class="bi bi-cart3"></i></a></li>
                </ul>
            </nav>
            
        </div>
    </header>
    
    <div id="contenido">
        
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <div class="icons footer__align">
            <a class="icon icon__instagram" href="#"><i class="bi bi-instagram"></i></a>
            <a class="icon icon__twitter" href="#" ><i class="bi bi-twitter"></i></a>
            <a class="icon icon__github" href="#" ><i class="bi bi-github"></i></a>
            <a class="icon icon__subir" href="#"><i class="bi bi-arrow-bar-up"></i></a>
        </div>
        <a href="#" class="subir">Ir a arriba</a>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/menu.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
                "tittle": "Felicitaciones",
                "text": "{{m}}",
                "icon": "success"
            })
        </script>
    {% endfor %}
    {% endif %}

    {% block js %}
        <script>
            let menu = document.getElementById("menu")
            let header = document.getElementById("header")
            let nav = document.getElementById("nav")
            menu.addEventListener("click", function () {
                if (header.style.height == "60px" || header.offsetHeight == 60) {
                    header.style.height = 60 + nav.offsetHeight + "px"
                } else {
                    header.style.height = "60px"
                }
            });

            window.addEventListener("resize", function () {
                let anchoVentana = document.documentElement.clientWidth
                if (anchoVentana > 480) {
                    header.style = "none"
                }
            });
        </script>
    {% endblock %}
</body>
</html>

app/templates/app/carrito.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Carrito{% endblock title %}
{% block content %}
<title>Carrito - Tiendita</title>
</head>
<body class="gradient-custom">
    {% load humanize %}
    <section class="vh-50">
        <div class="container py-5">
            <div class="row d-flex justify-content-center">
                <div class="col-12 col-md-8  ">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <h2>Carrito</h2>
                            <ul class="list-group" id="carrito"></ul>
                            <hr>
                            <div class="">
                                <ul>
                                    <li class="submenu">
                                        <div class="" id="carrito">
                                            <table class="table text-white">
                                                <thead>
                                                    <tr>
                                                        <th scope="col">Codigo Producto</th>
                                                        <th scope="col">Nombre</th>
                                                        <th scope="col">Precio</th>
                                                        <th scope="col">Descripcion</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <th scope="row">UYH347F</th>
                                                        <td>Macetero lucido</td>
                                                        <td>$19.546</td>
                                                        <td>Macetero entero loco</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">3082874</th>
                                                        <td>Flores de weed</td>
                                                        <td>$15.454</td>
                                                        <td>Flores con weed</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">87543985</th>
                                                        <td> Arbusto de leche </td>
                                                        <td>$13.648</td>
                                                        <td>Arbusto con leche descremada</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <p class="text-right">Total: 34.649<span id="total"></span>$</p>
                            <button class="btn btn-danger" id="boton-vaciar">Vaciar</button>
                            <button class="btn btn-primary" id="boton-comprar">Comprar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</body>

</html>
{% endblock %}

app/templates/app/catalogo.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Catalogo{% endblock title %}
{% block content %}
{% load humanize %}
{% load humanize %}
<br>
<br>
<br>
<h2 class="h1">Productos de nuestra tienda!</h2>
<div class="container productos mt-5">
    {% for p in productos %}
    <div class="producto d-flex justify-content-center">
        <div class="card contenedor_producto border border-dark rounded-4" style=" background-color: rgb(122, 217, 200);">
            {% if p.imagen %}
            <img class="card-img-top" src="{{ p.imagen.url }}" style="width:100%; padding:1%;" alt="imagen producto" >
            {% endif %}
            <div class="card-body detalle" style="background-color: rgb(151, 237, 236);">
                <h5>Categoria: {{ p.nombreCat | capfirst }}</h5>
                <h2>{{ p.nombreProducto | title }}</h2>
                <h5>Descripcion: {{ p.descripcionProducto | capfirst }}</h5>
                <h3>Precio: ${{ p.precioProducto | intcomma }}</h3>
                <button class="btn btn-success btnComprar">Comprar</button>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<br>
<br>
<br>
{% endblock %}

app/templates/app/clima.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Clima{% endblock title %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="JS/script.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Pagina Inicial</title>
</head>
<body>
    <br>
    <br>
    <br>
    <br>
<div class="container mb-4">
    <div class="card bg-dark text-white">
        <div class="card-body ">
            <h2>Informate de tu Clima y T°!</h2>
            <hr>
            <button class="btn btn-primary container align-items-center" id="btnLocalizar">Localizar</button>
            </div>
            <table class="table table-dark table-striped table-hover table-responsive-sm fs-4">
                <tr>
                    <th>Ciudad/Comuna</th>
                    <th>Clima Actual</th>
                    <th>T° Actual</th>
                    <th>T° Minima</th>
                    <th>T° Maxima</th>
                </tr>
                <tr id="resultado"></tr>
            </table>
        </div>
        <br>
        <br>
        <br>
    </div>
    <script>
        var x = document.getElementById("resultado");
        $("#btnLocalizar").click(function () {
            navigator.geolocation.getCurrentPosition(function (position) {
                let lat = position.coords.latitude;
                let long = position.coords.longitude;

                $.get("https://api.openweathermap.org/data/2.5/weather?lat=" + lat + "&lon=" + long + "&lang=sp&units=metric&appid=e7f7bdc257804d7dd9bc1b7af07e2a26", function (data) {
                    console.log(data);
                    $("#resultado").empty();
                    $("#resultado").append("<td>" + data.name + "</td>");
                    if (data.weather[0].main == "Clear") {
                        $("#resultado").append("<td> Despejado</td>");
                    } else if (data.weather[0].main == "Cloudy") {
                        $("#resultado").append("<td> Nublado</td>");
                    } else {
                        $("#resultado").append("<td>" + data.weather[0].main + "</td>");
                    }
                    $("#resultado").append("<td>" + Math.round(data.main.temp) + "</td>");
                    $("#resultado").append("<td>" + Math.round(data.main.temp_min) + "</td>");
                    $("#resultado").append("<td>" + Math.round(data.main.temp_max) + "</td>");
                    $("#resultado").append("<tr>");
                });
            });
        });
    </script>
    <br>
    <br>
    <br>
</body>
</html>
{% endblock %}

app/templates/app/contacto.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Contacto{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
<section class="vh-50 section__contacto">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-md-5 mt-md-4 pb-5">
                                <h2 class="fw-bold mb-2 text-uppercase">Contactanos!</h2>
                                {{ form | crispy }}
                                <button class="btn btn-primary" id="btnEnviar" type="submit" >Enviar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ mensaje }}
</section>
{% endblock %}

app/templates/app/home.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <div class="welcome">
        <h2>Bienvenido, @{{ user.username }}!</h2>
    </div>
    {% else %}
    <div class="welcome">
        <h2>Bienvenido!</h2>
    </div>
    {% endif %}
    <hr>
    <section class="suscribirse">
        <img src="{% static 'img/fondo.jpg' %}" alt="Foto">
        <div class="suscribirse__letras">
            <h2 class="suscribirse__mensaje">Suscribirse a "Oni-chan", una fundación sin fines de lucro. Al suscribirse obtendrá un descuento del 5% de forma permanente uwu</h2>
        </div>
        <button class="suscribirse__boton" href="#">Suscribirse</button>
    </section>
    <hr>
{% endblock %}

app/templates/app/pagar.html
{% extends 'app/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/stail2.css' %}">
<section class="vh-10">
    <div class="container py-5 h-10">
        <div class="pago__grid">
            <div class="row d-flex justify-content-center align-items-center" style="margin-right: 6.5rem; margin-left: 1.5rem;">
                <div class="card bg-dark text-white pago__size" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <h2 class="fw-bold mb-2 text-uppercase">Carrito de compras</h2>
                    </div>
                </div>
            </div>
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5 pago__dimention">
                    <div class="card bg-dark text-white pago__width" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <div class="mb-md-5 mt-md-4 pb-5">
                                <h2 class="fw-bold mb-2 text-uppercase">Pago</h2>
                                <p class="text-white-50 mb-5">Metodos de pago</p>
                                <form id="registro">
                                    <div class="form-group edit">
                                        <div class="form-outline form-white mb-4">
                                            <label class="form-label fw-bold fs-4">Precio final:</label>
                                            <span class="form-label fw-bold fs-4">$</span>
                                            <span class="form-label fw-bold fs-4" id="pago">0</span>
                                        </div>
                                        <div class="form-outline form-white mb-4">
                                            <label class="form-label fw-bold fs-4">Cupon de descuento:</label>
                                            <input type="text" class="form-control form-control-lg"/>
                                        </div>
                                        <div class="form-outline form-white mb-4">
                                            <label for="InputAddress" class="form-label fw-bold fs-4">Metodo de pago: </label>
                                            <select class="form-select fs-5">
                                                <option active>Metodo de pago</option>
                                                <option value="1">Tranferencia bancaria</option>
                                                <option value="2">Tarjeta de credito</option>
                                                <option value="3">Tarjeta de debito</option>
                                            </select>
                                        </div>
                                        <label class="form-label fw-bold fs-4"> Comentarios:</label>
                                        <div class="form-floating">
                                            <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px; resize: none;"></textarea>
                                        </div>
                                    </div>
                                    <div>
                                        <input type="reset" class="btn btn-outline-light btn-lg px-5 tamanno" id="btnCancelar" value="Cancelar">
                                        <input type="submit" class="btn btn-outline-light btn-lg px-5 tamanno" id="btnPagar" value="Pagar">
                                    </div>
                                </form>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}